# Generated by Django 4.1.7 on 2023-05-09 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('ingridients', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('warning', models.TextField()),
                ('image', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=120)),
                ('review', models.CharField(max_length=150)),
                ('function', models.CharField(max_length=50)),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skincare_recommendation_app.producttype')),
            ],
        ),
    ]
