# Generated by Django 4.1.7 on 2023-03-14 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skincare_recommendation_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
