# Generated by Django 4.1.7 on 2023-03-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare_recommendation_app', '0002_rename_products_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
    ]
